"""Generate the complete data dictionary and evidence-based coverage report."""
from pathlib import Path
import json, sqlite3

root = Path.cwd()
manifest = json.loads((root / 'data/manifest.json').read_text(encoding='utf-8'))
schema_dir = root / 'info/schema'
schema_dir.mkdir(parents=True, exist_ok=True)
index = ['# Snapshot data dictionary', '', 'Generated by `python scripts/document-snapshot.py` from `data/manifest.json`.', '',
         'These are observed database field names and types. Field semantics remain those of the imported AoWoW/client source; an undocumented field is not given an invented interpretation.', '',
         '| Source | SQLite file | Rows | Definition |', '| --- | --- | ---: | --- |']
for file in manifest['files']:
    for table in file['tables']:
        name = file['sourceSchema'] + '.' + table['name']
        lines = [f'# {name}', '', f"SQLite file: `{file['file']}`. Source object: {table['sourceKind']}. Rows: **{table['rows']:,}**.", '',
                 'Primary key: ' + (', '.join(f'`{key}`' for key in table['primaryKey']) or 'none recorded') + '.', '',
                 '| Column | PostgreSQL type | SQLite type | Nullable |', '| --- | --- | --- | --- |']
        for col in table['columns']:
            lines.append(f"| `{col['name']}` | `{col['postgresType']}` | {col['sqliteType']} | {'no' if col['notNull'] else 'yes'} |")
        lines += ['', 'See [type conversions](sqlite-format.md) and [the research map](../README.md).', '']
        (schema_dir / (name + '.md')).write_text('\n'.join(lines), encoding='utf-8')
        index.append(f"| `{name}` | `{file['file']}` | {table['rows']:,} | [Columns]({name}.md) |")
(schema_dir / 'README.md').write_text('\n'.join(index) + '\n', encoding='utf-8')

game = sqlite3.connect((root / 'data/game.db').as_uri() + '?mode=ro', uri=True)
game.execute("ATTACH DATABASE ? AS derived", (str(root / 'data/community-game.db'),))
counts = {file['sourceSchema'] + '.' + table['name']: table['rows'] for file in manifest['files'] for table in file['tables']}
queries = {
    'Items with placeholder or blank names': "SELECT count(*) FROM aowow_items WHERE name_loc0 IS NULL OR trim(name_loc0)='' OR name_loc0='Item #' || id",
    'Items without any stored tooltip row': 'SELECT count(*) FROM aowow_items i LEFT JOIN derived.item_tooltips t ON t.item_id=i.id WHERE t.item_id IS NULL',
    'Stored tooltip rows without a matching item': 'SELECT count(*) FROM derived.item_tooltips t LEFT JOIN aowow_items i ON i.id=t.item_id WHERE i.id IS NULL',
    'Parsed effect rows without a matching item': 'SELECT count(*) FROM derived.item_tooltip_effects t LEFT JOIN aowow_items i ON i.id=t.item_id WHERE i.id IS NULL',
    'Named items with iconId=0 or a missing icon reference': "SELECT count(*) FROM aowow_items i LEFT JOIN aowow_icons icon ON icon.id=i.iconId WHERE i.name_loc0 IS NOT NULL AND i.name_loc0 <> 'Item #' || i.id AND (i.iconId=0 OR icon.id IS NULL)",
}
report = ['# Published snapshot findings', '', f"Export started at **{manifest['exportedAt']}** (UTC). This is the export time, not a claim that the game was scraped at that time.", '',
          f"The release contains **{len(counts)} tables** with **{sum(counts.values()):,} rows**, including empty tables. Rows across related tables are not unique game entities.", '',
          '## Main datasets', '', '| Dataset | Exact rows |', '| --- | ---: |']
for name in ['game.aowow_items','game.aowow_spell','app.item_tooltips','app.item_tooltip_effects','app.item_versions','game.aowow_talent_tree_nodes','game.aowow_talent_tree_node_ranks','app.atlasloot_entries']:
    report.append(f'| `{name}` | {counts.get(name, 0):,} |')
report += ['', '## Coverage checks', '', 'These counts are computed from the released SQLite files. The query is included so the finding can be reproduced.', '']
for label, sql in queries.items():
    value = game.execute(sql).fetchone()[0]
    report += [f'**{label}: {value:,}.**', '', '```sql', sql + ';', '```', '']
report += ['## Talent source markers', '', '| Source | Class ID | Nodes |', '| --- | ---: | ---: |']
for source, class_id, count in game.execute('SELECT source, ownerClassId, count(*) FROM aowow_talent_tree_nodes GROUP BY source, ownerClassId ORDER BY ownerClassId, source'):
    report.append(f'| `{source}` | {class_id} | {count:,} |')
report += ['', '## Empty exported tables', '', 'Empty means no rows in this snapshot, not that the corresponding game feature does not exist.', '']
report += [f'- `{name}`' for name, count in counts.items() if count == 0]
report += ['', '## Missing source tables', '']
report += [f'- `{name}`' for name in manifest['missingTables']] or ['None.']
report += ['', '## Files and checksums', '', '| File | Bytes | SHA-256 |', '| --- | ---: | --- |']
for file in manifest['files']:
    report.append(f"| `{file['file']}` | {file['bytes']:,} | `{file['sha256']}` |")
    report.append(f"| `{file['compressedFile']}` | {file['compressedBytes']:,} | `{file['compressedSha256']}` |")
report += ['', 'See [the complete dictionary](schema/README.md), [manifest](../data/manifest.json), and [known limitations](known-gaps.md).', '']
(root / 'info/snapshot.md').write_text('\n'.join(report), encoding='utf-8')
game.close()
print(f'Documented {len(counts)} tables and generated coverage findings.')
