import { existsSync } from "node:fs";
import { Pool } from "pg";

if (existsSync(".env")) {
  process.loadEnvFile(".env");
}

const AOWOW_SCHEMA_URL =
  "https://raw.githubusercontent.com/azerothcore/aowow/master/setup/db_structure.sql";

const connectionString = process.env.GAME_DATABASE_URL || process.env.DATABASE_URL;
const targetSchema = process.env.GAME_DATABASE_SCHEMA || "game";

function quoteIdent(identifier: string) {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(identifier)) {
    throw new Error(`Unsafe SQL identifier: ${identifier}`);
  }

  return `"${identifier}"`;
}

function makeIdentifier(...parts: string[]) {
  const normalized = parts
    .join("_")
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");

  return normalized.slice(0, 60) || "idx";
}

function splitColumns(body: string) {
  const lines: string[] = [];
  let current = "";
  let depth = 0;
  let inString = false;

  for (const char of body) {
    if (char === "'" && !current.endsWith("\\")) {
      inString = !inString;
    }

    if (!inString) {
      if (char === "(") depth += 1;
      if (char === ")") depth -= 1;
    }

    if (char === "," && depth === 0 && !inString) {
      lines.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }

  if (current.trim()) {
    lines.push(current.trim());
  }

  return lines;
}

function convertDefault(value: string) {
  return value
    .replace(/DEFAULT b'([01])'/gi, "DEFAULT $1")
    .replace(/DEFAULT _utf8mb4'([^']*)'/gi, "DEFAULT '$1'")
    .replace(/DEFAULT current_timestamp\(\)/gi, "DEFAULT CURRENT_TIMESTAMP")
    .replace(/DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP/gi, "DEFAULT CURRENT_TIMESTAMP");
}

function convertColumn(line: string) {
  const match = line.match(/^`([^`]+)`\s+([\s\S]+)$/);

  if (!match) {
    return null;
  }

  const [, name, rawRest] = match;
  let rest = rawRest
    .replace(/\s+COMMENT\s+'(?:\\'|[^'])*'/gi, "")
    .replace(/\s+COLLATE\s+\w+/gi, "")
    .replace(/\s+CHARACTER SET\s+\w+/gi, "")
    .replace(/\s+UNSIGNED/gi, "")
    .replace(/\s+SIGNED/gi, "")
    .replace(/\s+ZEROFILL/gi, "")
    .replace(/\s+AUTO_INCREMENT/gi, " GENERATED BY DEFAULT AS IDENTITY")
    .replace(/\s+ON UPDATE CURRENT_TIMESTAMP/gi, "")
    .replace(/\btinyint\s*\(\s*\d+\s*\)/gi, "smallint")
    .replace(/\bsmallint\s*\(\s*\d+\s*\)/gi, "smallint")
    .replace(/\bmediumint\s*\(\s*\d+\s*\)/gi, "integer")
    .replace(/\bint\s*\(\s*\d+\s*\)/gi, "integer")
    .replace(/\bbigint\s*\(\s*\d+\s*\)/gi, "bigint")
    .replace(/\btinyint\b/gi, "smallint")
    .replace(/\bmediumint\b/gi, "integer")
    .replace(/\bint\b/gi, "integer")
    .replace(/\bdouble\s*\((\d+)\s*,\s*(\d+)\)/gi, "numeric($1,$2)")
    .replace(/\bfloat\s*\((\d+)\s*,\s*(\d+)\)/gi, "numeric($1,$2)")
    .replace(/\bdouble\b/gi, "double precision")
    .replace(/\bfloat\b/gi, "real")
    .replace(/\bdatetime\b/gi, "timestamp")
    .replace(/\bmediumtext\b/gi, "text")
    .replace(/\blongtext\b/gi, "text")
    .replace(/\btinytext\b/gi, "text")
    .replace(/\bvarbinary\((\d+)\)/gi, "bytea")
    .replace(/\bblob\b/gi, "bytea")
    .replace(/\benum\([^)]+\)/gi, "text")
    .replace(/`/g, "\"");

  rest = convertDefault(rest);

  return `${quoteIdent(name)} ${rest}`;
}

function convertConstraint(line: string) {
  const primary = line.match(/^PRIMARY KEY\s+\((.+)\)$/i);
  if (primary) {
    return `PRIMARY KEY (${primary[1].replace(/`([^`]+)`/g, (_, name) => quoteIdent(name))})`;
  }

  return null;
}

function convertIndex(tableName: string, line: string) {
  const match = line.match(/^(UNIQUE\s+)?(?:FULLTEXT\s+|SPATIAL\s+)?KEY\s+`([^`]+)`\s+\((.+)\)$/i);

  if (!match) {
    return null;
  }

  const [, unique, keyName, rawColumns] = match;
  const columns = rawColumns
    .split(",")
    .map((column) => column.trim().replace(/`([^`]+)`(?:\(\d+\))?/g, (_, name) => quoteIdent(name)))
    .join(", ");
  const indexName = quoteIdent(makeIdentifier(tableName, keyName, unique ? "uidx" : "idx"));

  return `CREATE ${unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${indexName} ON ${quoteIdent(targetSchema)}.${quoteIdent(tableName)} (${columns});`;
}

function convertCreateTables(mysqlSql: string) {
  const blocks = Array.from(
    mysqlSql.matchAll(/CREATE TABLE `([^`]+)` \(([\s\S]*?)\)\s+ENGINE=/g),
  );

  return blocks.map((block) => {
    const [, tableName, body] = block;
    const parts = splitColumns(body);
    const converted = parts
      .map((line) => convertColumn(line) ?? convertConstraint(line))
      .filter((line): line is string => Boolean(line));
    const indexes = parts
      .map((line) => convertIndex(tableName, line))
      .filter((line): line is string => Boolean(line));

    return {
      tableName,
      sql: `CREATE TABLE IF NOT EXISTS ${quoteIdent(targetSchema)}.${quoteIdent(tableName)} (\n  ${converted.join(",\n  ")}\n);`,
      indexes,
    };
  });
}

function helperTableStatements() {
  const schema = quoteIdent(targetSchema);

  return [
    {
      tableName: "aowow_talent_tree_tabs",
      sql: `
CREATE TABLE IF NOT EXISTS ${schema}.aowow_talent_tree_tabs (
  id text NOT NULL,
  "treeKey" text NOT NULL DEFAULT '',
  "treeType" text NOT NULL DEFAULT '',
  "ownerClassId" integer NOT NULL DEFAULT 0,
  "ownerClassName" text NOT NULL DEFAULT '',
  "ownerSpecId" integer NOT NULL DEFAULT 0,
  "ownerSpecName" text NOT NULL DEFAULT '',
  "ownerSpecSkillId" integer NOT NULL DEFAULT 0,
  "tabTypeId" integer NOT NULL DEFAULT 0,
  "tabName" text NOT NULL DEFAULT '',
  "orderIndex" integer NOT NULL DEFAULT 0,
  "backgroundAtlas" text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT ''
);`,
      indexes: [
        `CREATE INDEX IF NOT EXISTS aowow_talent_tree_tabs_owner_idx ON ${schema}.aowow_talent_tree_tabs ("ownerClassId", "ownerSpecId");`,
      ],
    },
    {
      tableName: "aowow_talent_tree_nodes",
      sql: `
CREATE TABLE IF NOT EXISTS ${schema}.aowow_talent_tree_nodes (
  id integer NOT NULL,
  "treeKey" text NOT NULL DEFAULT '',
  "treeType" text NOT NULL DEFAULT '',
  "ownerClassId" integer NOT NULL DEFAULT 0,
  "ownerClassName" text NOT NULL DEFAULT '',
  "ownerSpecId" integer NOT NULL DEFAULT 0,
  "ownerSpecName" text NOT NULL DEFAULT '',
  "ownerSpecSkillId" integer NOT NULL DEFAULT 0,
  "tabTypeId" integer NOT NULL DEFAULT 0,
  "tabName" text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT '',
  "parentId" integer NOT NULL DEFAULT 0,
  "groupId" integer NOT NULL DEFAULT 0,
  row integer NOT NULL DEFAULT 0,
  col integer NOT NULL DEFAULT 0,
  name text NOT NULL DEFAULT '',
  icon text NOT NULL DEFAULT '',
  "iconId" integer NOT NULL DEFAULT 0,
  "maxRanks" integer NOT NULL DEFAULT 0,
  "spellId" integer NOT NULL DEFAULT 0,
  "allSpellIds" text NOT NULL DEFAULT '',
  prerequisite text NOT NULL DEFAULT '',
  anchor text NOT NULL DEFAULT '',
  color text NOT NULL DEFAULT '',
  shape text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT ''
);`,
      indexes: [
        `CREATE INDEX IF NOT EXISTS aowow_talent_tree_nodes_tree_idx ON ${schema}.aowow_talent_tree_nodes ("treeKey", row, col);`,
        `CREATE INDEX IF NOT EXISTS aowow_talent_tree_nodes_spell_idx ON ${schema}.aowow_talent_tree_nodes ("spellId");`,
      ],
    },
    {
      tableName: "aowow_talent_tree_node_ranks",
      sql: `
CREATE TABLE IF NOT EXISTS ${schema}.aowow_talent_tree_node_ranks (
  id text NOT NULL,
  "advancementId" integer NOT NULL DEFAULT 0,
  rank integer NOT NULL DEFAULT 0,
  "spellId" integer NOT NULL DEFAULT 0,
  "spellName" text NOT NULL DEFAULT '',
  "iconId" integer NOT NULL DEFAULT 0,
  "treeKey" text NOT NULL DEFAULT '',
  "treeType" text NOT NULL DEFAULT '',
  "ownerClassId" integer NOT NULL DEFAULT 0,
  "ownerSpecId" integer NOT NULL DEFAULT 0,
  "ownerSpecSkillId" integer NOT NULL DEFAULT 0,
  "tabTypeId" integer NOT NULL DEFAULT 0
);`,
      indexes: [
        `CREATE INDEX IF NOT EXISTS aowow_talent_tree_node_ranks_spell_idx ON ${schema}.aowow_talent_tree_node_ranks ("spellId");`,
        `CREATE INDEX IF NOT EXISTS aowow_talent_tree_node_ranks_node_idx ON ${schema}.aowow_talent_tree_node_ranks ("advancementId", rank);`,
      ],
    },
  ];
}

async function main() {
  if (!connectionString) {
    throw new Error("GAME_DATABASE_URL or DATABASE_URL must be set.");
  }

  const response = await fetch(AOWOW_SCHEMA_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch AoWoW schema: ${response.status}`);
  }

  const mysqlSql = await response.text();
  const statements = convertCreateTables(mysqlSql);
  const helpers = helperTableStatements();
  const pool = new Pool({ connectionString });
  const schema = quoteIdent(targetSchema);

  await pool.query(`CREATE SCHEMA IF NOT EXISTS ${schema}`);

  for (const statement of [...statements, ...helpers]) {
    try {
      await pool.query(statement.sql);
      for (const indexSql of statement.indexes) {
        await pool.query(indexSql);
      }
    } catch (error) {
      console.error(`Failed while creating ${targetSchema}.${statement.tableName}`);
      console.error(statement.sql);
      throw error;
    }
  }

  await pool.end();
  console.log(
    `Created/verified ${statements.length} AoWoW-compatible tables and ${helpers.length} helper tables in schema ${targetSchema}.`,
  );
  console.log("This initializes schema only. Populate data from AoWoW/AzerothCore import outputs before production use.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
