import { once } from "node:events";
import {
  createReadStream,
  createWriteStream,
  existsSync,
  rmSync,
  mkdirSync,
  readdirSync,
  statSync,
  type WriteStream,
} from "node:fs";
import path from "node:path";

const inputPath = process.argv[2] || path.join("output", "addon", "tooltip");
const outputPath = process.argv[3] || `${inputPath}-split`;
const recordsPerFile = Math.max(1, Number(process.argv[4] || 5000));

function addonInputFiles(input: string, outputDir: string) {
  const resolved = path.resolve(input);
  const resolvedOutput = path.resolve(outputDir);
  const stat = statSync(resolved);
  if (stat.isFile()) return [resolved];
  if (!stat.isDirectory()) {
    throw new Error(`Input is neither a file nor a directory: ${input}`);
  }

  const files: string[] = [];
  const walk = (dir: string) => {
    if (path.resolve(dir) === resolvedOutput) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const entryPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(entryPath);
      } else if (entry.isFile() && entry.name.toLowerCase().endsWith(".lua")) {
        files.push(entryPath);
      }
    }
  };
  walk(resolved);
  files.sort((left, right) => left.localeCompare(right));

  if (files.length === 0) {
    throw new Error(`No .lua files found in ${input}`);
  }

  return files;
}

function leadingIndentWidth(line: string) {
  return line.match(/^\s*/)?.[0].length ?? 0;
}

function isTableClose(line: string) {
  return /^\s*},?\s*(?:--.*)?$/.test(line);
}

function itemTableStart(line: string) {
  return line.match(/^(\s*)(?:\["items"\]|items)\s*=\s*\{\s*,?\s*(?:--.*)?$/);
}

function itemRecordStart(line: string) {
  return /^\s*(?:\[\d+\]\s*=\s*\{|\{\s*,?\s*(?:--.*)?$)/.test(line);
}

function safePrefix(file: string) {
  const base = path.basename(file, path.extname(file));
  return base.replace(/[^a-zA-Z0-9._-]+/g, "_");
}

async function* readLines(file: string) {
  let carry = "";
  for await (const chunk of createReadStream(file, { encoding: "utf8" })) {
    carry += chunk;
    const lines = carry.split("\n");
    carry = lines.pop() ?? "";
    for (const line of lines) {
      yield line.endsWith("\r") ? line.slice(0, -1) : line;
    }
  }

  if (carry) {
    yield carry.endsWith("\r") ? carry.slice(0, -1) : carry;
  }
}

function removeExistingChunks(outputDir: string, prefix: string) {
  const chunkPattern = new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}-part-\\d+\\.lua$`);
  for (const entry of readdirSync(outputDir, { withFileTypes: true })) {
    if (entry.isFile() && chunkPattern.test(entry.name)) {
      rmSync(path.join(outputDir, entry.name), { force: true });
    }
  }
}

async function writeChunk(writer: WriteStream, text: string) {
  if (!writer.write(text)) await once(writer, "drain");
}

async function closeWriter(writer: WriteStream | null) {
  if (!writer) return;
  writer.end();
  await once(writer, "finish");
}

async function splitFile(file: string, outputDir: string) {
  const prefix = safePrefix(file);
  const relative = path.relative(process.cwd(), file) || file;
  removeExistingChunks(outputDir, prefix);
  let writer: WriteStream | null = null;
  let part = 0;
  let recordsInPart = 0;
  let totalRecords = 0;

  const openChunk = async () => {
    part += 1;
    recordsInPart = 0;
    const chunkPath = path.join(outputDir, `${prefix}-part-${String(part).padStart(4, "0")}.lua`);
    writer = createWriteStream(chunkPath, { encoding: "utf8" });
    await writeChunk(
      writer,
      [
        "-- Auto-generated by pnpm game:split-scraper.",
        `-- Source: ${relative}`,
        "AscensionScraperDB = {",
        '  ["items"] = {',
        "",
      ].join("\n"),
    );
  };

  const flushRecord = async (lines: string[]) => {
    if (lines.length === 0) return;
    if (!writer || recordsInPart >= recordsPerFile) {
      if (writer) {
        await writeChunk(writer, '  },\n  ["spells"] = {},\n  ["spellbook"] = {},\n  ["trainerServices"] = {},\n}\n');
        await closeWriter(writer);
      }
      await openChunk();
    }

    await writeChunk(writer!, lines.join("\n"));
    await writeChunk(writer!, "\n");
    recordsInPart += 1;
    totalRecords += 1;
  };

  let inItems = false;
  let itemsIndent = 0;
  let recordIndent: number | null = null;
  let recordLines: string[] = [];

  for await (const line of readLines(file)) {
    if (!inItems) {
      const match = itemTableStart(line);
      if (match) {
        inItems = true;
        itemsIndent = match[1].length;
        recordIndent = null;
      }
      continue;
    }

    const indent = leadingIndentWidth(line);
    if (indent <= itemsIndent && isTableClose(line)) {
      await flushRecord(recordLines);
      recordLines = [];
      inItems = false;
      continue;
    }

    const startsRecord = itemRecordStart(line) && indent > itemsIndent;
    if (startsRecord && (recordIndent === null || indent === recordIndent)) {
      if (recordIndent === null) recordIndent = indent;
      await flushRecord(recordLines);
      recordLines = [line];
      continue;
    }

    if (recordLines.length > 0) recordLines.push(line);
  }

  await flushRecord(recordLines);
  if (writer) {
    await writeChunk(writer, '  },\n  ["spells"] = {},\n  ["spellbook"] = {},\n  ["trainerServices"] = {},\n}\n');
    await closeWriter(writer);
  }

  return { file, parts: part, records: totalRecords };
}

async function main() {
  if (!existsSync(inputPath)) {
    throw new Error(`Input path not found: ${inputPath}`);
  }

  mkdirSync(outputPath, { recursive: true });
  const files = addonInputFiles(inputPath, outputPath);
  console.log(`Splitting ${files.length} Lua file(s) into ${path.resolve(outputPath)}`);
  console.log(`Records per output file: ${recordsPerFile}`);

  let totalParts = 0;
  let totalRecords = 0;
  for (const file of files) {
    const result = await splitFile(file, outputPath);
    totalParts += result.parts;
    totalRecords += result.records;
    const relative = path.relative(process.cwd(), result.file) || result.file;
    console.log(`${relative}: records=${result.records} parts=${result.parts}`);
  }

  console.log(`Done. Wrote ${totalParts} file(s), ${totalRecords} item record(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
